### ISSUE TITLE
travis builds are broken for dune-gdt forks

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt-super#1]
This is just a place to document some things. All forks of dune-gdt and branches which derive from dune-gdt/master have automatic travis builds enbaled (luckily). As such, they rely on dune-gdt-super to yield a fully usable build environment (including all relevant dependencies and grids).
Thus, the dune-gdt-super master _should always be fine_! (In contrast to the dune-gdt master, which might be broken). I thus propose to test major changes as the move towards dune-alugrid and the 2.4 core modules in a separate branch within dune-gdt-super.

Consequently, the testing branch in dune-gdt has to checkout the corresponding branch in the super module first. However, travis builds for all other branches and forks continue to function as they should and I believe this is worth the effort.

**Comment by ftalbrecht** [comment]
This is reflected in #2 and the updated (aka resetted to pre dune-2.4) master branch. The `travis_updates` branch in dune-gdt was updated accordingly...

**Comment by renefritze** [comment]
I've enabed branch protection for master. If I understand it correctly the corresponding travis build, ie. submodule checkout, needs to pass for a push to be accepted.
