### ISSUE TITLE
Fix download of Alberta

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-gdt-super#5]
The link for alberta in the ``external-libraries.cfg`` seems to be broken. I did not find a new one, so I just commented that section out for now. I we still want to have Alberta as external library, we need to fix the link.

**Comment by renefritze** [comment]
Somewhat related: does the Alberta from Debian still work with the 2.6 modules?

**Comment by tobiasleibner** [comment]
I don't know, are we using Alberta in any of our CI setups?

**Comment by renefritze** [comment]
Grep says some of the subdomain tests would, if it's found. I have no idea if those tests actually run though, hence the ask.

**Comment by tobiasleibner** [comment]
Yes, I think at least some of the tests use Alberta, e.g., https://travis-ci.org/dune-community/dune-xt-grid/jobs/484270251. In that build, Alberta is found and used.

**Comment by renefritze** [comment]
Great. Thanks!

**Comment by tobiasleibner** [comment]
I still cannot find a new download link for Alberta. Maybe we should simply remove Alberta from our setup?

**Comment by renefritze** [comment]
https://gitlab.mathematik.uni-stuttgart.de/ians-nmh/alberta/alberta3/-/releases
via https://dune-project.org/doc/install-alberta/

**Comment by tobiasleibner** [comment]
Ah, nice.

**Comment by tobiasleibner** [comment]
Fixed in https://zivgitlab.uni-muenster.de/ag-ohlberger/dune-community/dune-gdt-super/-/commit/4c5549e6a3b22ce30b21ebc8718c81f310d01ced
