### ISSUE TITLE
refactor wheel publishing

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-gdt-super#8]
When updating dune-xt as well as dune-gdt, configure of dune-gdt fails since the required updated dune-xt wheel is not yet present. We should thus refactor building a bit
- separate builds of dune-xt and dune-gdt in different stages?
- publish dune-xt to the gitlab registry inbetween?
- configure pip to use this registry to allow dune-gdt to depend on the newly built version?

**Comment by tobiasleibner** [comment]
Moved to gitlab.
